### PR TITLE
share-kit react native lib

### PR DESCRIPTION
**Pull request by mul1sh**
Fixes https://github.com/hellobloom/share-kit/issues/51

### CODE REVIEW

**Comment by pbteja1998** [comment]
@mul1sh This is line to line copy of the code by @psdkumar. I have kept an eye on this issue since you told that you would want to work on this. You have been saying that you have been fixing final bugs..., doing final testing... etc kind of stuff. But I don't see any code that is different from @psdkumar's implementation. Even the color codes and css is exactly same. Also in one of the comments you told that you were fixing some storybook bugs... You don't even have a storybook implementation in this pr.

Please clarify because even I tried to work on this, but I could not do better than that of @psdkumar's implementation. Hence I gave up. I was looking forward to see how you did it. But if this pr has your actual code, you did not do anything from the last one month when this pr was first opened.

**Comment by mul1sh** [comment]
@pbteja1998 I sincerely don't know what you're ranting about! 👀 

I tried many approaches locally before I chose the current one and I didn't copy from anyone, but anyway carry on 😆

**Comment by pbteja1998** [comment]
I am sorry if I offended you in some way. It's just that I was waiting for this, then when you submitted your code, it looked exactly same as that of other person's code. Maybe it's just a coincidence.

Please don't mind my comment. Thanks and sorry once again for offending you. I just thought that you forgot to submit the actual code because it has no storybook implementation(but you were talking about it in one of the comments.)

OK, never mind anything I said. Keep up your work.

**Comment by JaceHensley** [comment]
@mul1sh if you can add directions on how to run storybook and build share-kit-reactnative I can take a look at this today :D

Looking at the `package.json#scripts` I'm wondering why `styles.js` isn't `.ts` and included in the regular tsc build step

**Comment by mul1sh** [comment]
@JaceHensley Sure no worries, I've added the instructions just now 😃 

Also I've fixed the `styles.js` and converted it to `styles.ts`, I actually hadn't noticed this on my end, thanks for pointing it out to me 🙂

**Comment by JaceHensley** [comment]
Awesome thanks. I'm trying to run the storybook but am getting this issue:

```
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
3 warnings
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
Note: /Users/jace/workspaces/share-kit-reactnative/example/node_modules/react-native-svg/android/src/main/java/com/horcrux/svg/TSpanView.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
3 warnings

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:validateSigningDebug'.
> Keystore file '/Users/jace/workspaces/share-kit-reactnative/example/android/app/debug.keystore' not found for signing config 'debug'.
```

I was hitting the issue about the Android SDK not being found before that but fixed that issue with `local.properties` file.

**Comment by mul1sh** [comment]
@JaceHensley sorry about this, you are missing the debug.keystore file which had been kept back by `.gitignore` on my end. But i've pushed it,  so kindly test again.

**Comment by mul1sh** [comment]
@JaceHensley sorry about this, it seems you are missing the `debug.keystore` file which had been kept back by `.gitignore` on my end. But i've pushed it,  so kindly test again.

**Comment by JaceHensley** [comment]
Nice, this looks really good. To publish we just need to build and include `dist/` right? Will be merging this shortly. 🎉

**Comment by mul1sh** [comment]
@JaceHensley Thanks and yes, to publish just include the `dist/` folder in the package and you'll be good to go 😃

**Pull request merged**
